spring.application.name=product-shop-service

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8090

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

info.app.name=product-shop-service
info.app.description=Financial Services Product Shop API
info.app.version=0.0.1